# -*- mode: ruby -*-
# vi: set ft=ruby :

FileUtils.mkdir_p './shared'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "rhel-lac"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

#   # Disable the default share of the current code directory. Doing this
#   # provides improved isolation between the vagrant box and your host
#   # by making sure your Vagrantfile isn't accessable to the vagrant box.
#   # If you use this you may want to enable additional shared subfolders as
#   # shown above.
#   config.vm.synced_folder ".", "/vagrant", disabled: true
#
#   # Share an additional folder to the guest VM. The first argument is
#   # the path on the host to the actual folder. The second argument is
#   # the path on the guest to mount the folder. And the optional third
#   # argument is a set of non-required options.
#   ##** seems like we may not need any of this, but keeping for now
end
