- hosts: localhost

  tasks:
    - name: Install awxkit
      ansible.builtin.pip:
        name: awxkit

    - name: Call role specific job_template
      awx.awx.job_launch:
        job_template: "Role1 Template"
        extra_vars:
          host: "{{ ip }}"
        controller_host: https://aap-automation-controller-aap.apps.ocp4-beta.vsap.local
        controller_password: wJXLvxg5n34Kk7R9mq8wRy0adq3q3zGc
        controller_username: admin
        controller_oauthtoken: n3MTIYGqeilhBq81AY9TOFLYdmZTxo
        validate_certs: no

