- hosts: "{{ host }}"

  tasks:
    - name: Print out host
      debug:
        msg: "Host is {{ host }}"

    - name: Create directory with all permissions
      ansible.builtin.file:
        path: ~/test_open
        state: directory
        mode: '0777'

    # Do role-based provisioning
