- hosts: localhost

  vars:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InZINFY0Njl6S2piY19rOFIyYm8xRzJyUnA3enhLaEMwTi1hajV3aWd3Z0kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTcwMTMwMzMyOCwiaWF0IjoxNzAxMjk5NzI4LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im9wZW5zaGlmdC1tb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtazhzIiwidWlkIjoiNmJlYjI1MTUtZTBjZS00NmVhLTgyOTAtZjZkMWFiM2JjMzVjIn19LCJuYmYiOjE3MDEyOTk3MjgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuc2hpZnQtbW9uaXRvcmluZzpwcm9tZXRoZXVzLWs4cyJ9.PYSS6VbMPTGPZlyRHBTBczUAQe9_9MEvw2Zl4YHT1Y0K6gyMBMUmKGBST01O9gbHYDLhIMLcNP_uIwam0SiF0IhVDjIhP5T08D2EmC8veCNnJHFqlYLZ2AUvsQiR6_fV5B9B7TSjR7EQ9e3oPCjDBAZaJgKrWpEZqlIBXCM6MPfVcFRSI7cHsV762BPE_Aiy7hgpz_chktWMBJbOQYnqdpAdHDEEyAVehPcj4PAMsC9knfoFWmISlURJxPBaDrXi5kujBhWubux7p5qtqEk89HOb55B6_Wtg_u7ADM2WZh7dHqdq1GhaU2qvYMoW2cVuC3RQ_pO0ri5z9-R3up9--9M8I1p7aY-fjYvkbiUxhQAgkXS9X_Wgv2192pDtq1hVztMuRcTa-HSzk3pmmnIBWfqETUyPeEUPf6jMdSE_aK9p0XojdAh7yxH7bz7OQl5fgJSPdWZOEbJnFfXKbH5j_o-q7rcHJvKS6z-iQuBUjSJBYmo7doaQjEHX-sm-5yMqUlDvhsNi8bPJFw5cqMpQoWNXbUpXvYl4POEF1aIwvacq5bOpLtIrcQrCazTmogbPWXW74cIqK4XU46UbH4RAL2f6wg8sVFAQy8GrxI-bWqPoEtdr7j5YAk9cofi7f_PqDmneJeXIqoP_XHUvXNfoZu0j4wHqRbQ99ktUiuKpZm8
    prometheus_route: https://prometheus-k8s-openshift-monitoring.apps.ocp4-beta.vsap.local/api
#    node_info: {
#      "status": "success",
#      "data": {
#        "resultType": "vector",
#        "result": [
#          {
#            "metric": {
#              "__name__": "kube_node_info",
#              "container": "kube-rbac-proxy-main",
#              "container_runtime_version": "cri-o://1.26.4-4.1.rhaos4.13.git92b763a.el9",
#              "endpoint": "https-main",
#              "internal_ip": "192.168.17.13",
#              "job": "kube-state-metrics",
#              "kernel_version": "5.14.0-284.36.1.el9_2.x86_64",
#              "kubelet_version": "v1.26.9+636f2be",
#              "kubeproxy_version": "v1.26.9+636f2be",
#              "namespace": "openshift-monitoring",
#              "node": "api.ocp4-beta.vsap.local.17.168.192.in-addr.arpa",
#              "os_image": "Red Hat Enterprise Linux CoreOS 413.92.202310210500-0 (Plow)",
#              "service": "kube-state-metrics",
#              "system_uuid": "4c4c4544-0058-5210-8044-b2c04f383533"
#            },
#            "value": [
#              1700590266.713,
#              "1"
#            ]
#          }
#        ]
#      }
#    }

  tasks:
    - name: Install awxkit
      ansible.builtin.pip:
        name: awxkit

#    - name: Look up node information
#      uri:
#        url: https://prometheus-k8s-openshift-monitoring.apps.ocp4-beta.vsap.local/api/v1/query?query=1
#        method: GET
#        headers:
#          Content-Type: application/json
#          Authorization: "Bearer sha256~cJHFyinVooFeAfcqGYAHzW6ShqdQcqpS9us7hZLarrk"
#          Accept: application/json
#        validate_certs: false
#      register: node_info

    # Tried using URI ansible module above but was getting 403.
    - name: Look up node information
      shell: 'curl -s -k -H "Authorization: Bearer {{ token }}" -G --data-urlencode "query=kube_node_info and on(node) label_replace(node_time_seconds - node_boot_time_seconds < 3000, \"node\", \"\$1\", \"instance\", \"(.*)\")" {{ prometheus_route }}/v1/query'
      register: node_info_output

    - name: Print out node lookup call
      debug:
        msg: "Node information is {{ node_info_output }}"

    - name: Set node info
      set_fact:
        node_info: "{{ node_info_output.stdout | from_json }}"

    - name: Print out node lookup call
      debug:
        msg: "Node information is {{ node_info }}"

    - name: Call role job template wrapper
      awx.awx.job_launch:
        job_template: "Provision {{ item.metric.internal_ip }}"
        extra_vars:
          ip: "{{ item.metric.internal_ip }}"
        controller_host: https://aap-automation-controller-aap.apps.ocp4-beta.vsap.local
        controller_password: wJXLvxg5n34Kk7R9mq8wRy0adq3q3zGc
        controller_username: admin
        controller_oauthtoken: n3MTIYGqeilhBq81AY9TOFLYdmZTxo
        validate_certs: no
      when: node_info.status == "success"
      loop: "{{ node_info.data.result }}"
