- hosts: localhost

  vars:
    ip: 192.168.1.1 # this ip should come from looking up the most recent started node
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InZINFY0Njl6S2piY19rOFIyYm8xRzJyUnA3enhLaEMwTi1hajV3aWd3Z0kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTcwMDU5NjkyOSwiaWF0IjoxNzAwNTkzMzI5LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im9wZW5zaGlmdC1tb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtazhzIiwidWlkIjoiNmJlYjI1MTUtZTBjZS00NmVhLTgyOTAtZjZkMWFiM2JjMzVjIn19LCJuYmYiOjE3MDA1OTMzMjksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuc2hpZnQtbW9uaXRvcmluZzpwcm9tZXRoZXVzLWs4cyJ9.hnaHHt0uIvWIfIT4B5Na7QiFzNfwjvuAQ6MOenE6cbO8Y1cFWBgbvZxBN-kDT0CZ9W1A-Spa4K9j3c9oPpT3fsOE1nphQlOEOb7XlF16G9tZDQSdTf-AAR9cZpEKJ02DpgKca2KkhEN2IOpEEWkIYIW6iqFh3nu3vnXj4vObxvFczxdrdE9-JVdsGkS1Ukq1m6RQ9StKV0metLzhWBf_HHFelngJ_ogKfTUFdDGsJ7NgwtaMtKlGBdJi2ctg9JF3bH0L7xRgQrdDq490MlulcJobuV6Xl0bCwqBVvxUFSIAF6U4fRLt8YGBl7OBBsJ226cgHUYcx7M0jnD0G3YBEf_w2uiY7brqYSccgW1UUCPCyThvadlwMg3X8tzCZnCpQx0nk4lIRs1N957y1dPGhKjXzJ71TD1d6CND2SpGzVQoKLHwdXX9DigaePqjE3uoZZUvBPDhoVLz0Cm79ltovpz9rQBuzQyChfd5Z4gmuTU-2AWk10rxCVCuWhCovs_ZwzW6gN0e1odZA1udaMaYtBwyngORdn1lBGkKBx6Ot2zLkg_X1Scqv49f2tJ8QPpSon7iwXuXRF1np8yiDaMAYinnyBq1Lv4J3KGUzjeQ4IDznVt1J5bPMi5uz6z7IXmJX5rMldCUmoa2HthPd2ANDpVifgSl4y9X2wTo9yym23n4
    prometheus_route: https://prometheus-k8s-openshift-monitoring.apps.ocp4-beta.vsap.local/api
#    node_info: {
#      "status": "success",
#      "data": {
#        "resultType": "vector",
#        "result": [
#          {
#            "metric": {
#              "__name__": "kube_node_info",
#              "container": "kube-rbac-proxy-main",
#              "container_runtime_version": "cri-o://1.26.4-4.1.rhaos4.13.git92b763a.el9",
#              "endpoint": "https-main",
#              "internal_ip": "192.168.17.13",
#              "job": "kube-state-metrics",
#              "kernel_version": "5.14.0-284.36.1.el9_2.x86_64",
#              "kubelet_version": "v1.26.9+636f2be",
#              "kubeproxy_version": "v1.26.9+636f2be",
#              "namespace": "openshift-monitoring",
#              "node": "api.ocp4-beta.vsap.local.17.168.192.in-addr.arpa",
#              "os_image": "Red Hat Enterprise Linux CoreOS 413.92.202310210500-0 (Plow)",
#              "service": "kube-state-metrics",
#              "system_uuid": "4c4c4544-0058-5210-8044-b2c04f383533"
#            },
#            "value": [
#              1700590266.713,
#              "1"
#            ]
#          }
#        ]
#      }
#    }

  tasks:
    - name: Install awxkit
      ansible.builtin.pip:
        name: awxkit

#    - name: Look up node information
#      uri:
#        url: https://prometheus-k8s-openshift-monitoring.apps.ocp4-beta.vsap.local/api/v1/query?query=1
#        method: GET
#        headers:
#          Content-Type: application/json
#          Authorization: "Bearer sha256~cJHFyinVooFeAfcqGYAHzW6ShqdQcqpS9us7hZLarrk"
#          Accept: application/json
#        validate_certs: false
#      register: node_info

    # Tried using URI ansible module above but was getting 403.
    - name: Look up node information
      shell: 'curl -s -k -H "Authorization: Bearer {{ token }}" -G --data-urlencode "query=kube_node_info and on(node) label_replace(node_time_seconds - node_boot_time_seconds < 150, \"node\", \"\$1\", \"instance\", \"(.*)\")" {{ prometheus_route }}/v1/query'
      register: node_info_output

    - name: Set node info
      set_fact:
        node_info: "{{ node_info_output.stdout | from_json }}"

    - name: Print out node lookup call
      debug:
        msg: "Node information is {{ node_info }}"

    - name: Call role job template wrapper
      awx.awx.job_launch:
        job_template: "Provision {{ ip }}"
        extra_vars:
          ip: "{{ item.metric.internal_ip }}"
        controller_host: https://aap-automation-controller-aap.apps.ocp4-beta.vsap.local
        controller_password: wJXLvxg5n34Kk7R9mq8wRy0adq3q3zGc
        controller_username: admin
        controller_oauthtoken: n3MTIYGqeilhBq81AY9TOFLYdmZTxo
        validate_certs: no
      when: node_info.status == "success"
      loop: "{{ node_info.data.result }}"
